
version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # GRPC API
    volumes:
      - qdrant_storate:/qudrant/storage
    environment:
      - QDRANT_ALLOW_RESET=true  # Allows collection drops for development
      - QDRANT_LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=jumo
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  postgres_data:
