
version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # GRPC API
    volumes:
      - qdrant_data:/qudrant/storage
    environment:
      - QDRANT_ALLOW_RESET=true  # Allows collection drops for development
      - QDRANT_LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
  postgres:
    env_file:
      - .env
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo
    ports:
      # IMPORTANT: MAPPING EXTERNAL PORT FROM DIFFERENT PORT NUMBER TO AVOID CONFLICTS WITH LOCAL INSTALL
      - 27019:27017
    volumes:
      - mongodb_data:/data/db

volumes:
  qdrant_data:
  postgres_data:
